// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"1024","screenHeight":"576","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"ゲーム起動時にRPG Makerおよびユーザーロゴを表示します。","parameters":{"logo1":"","logo1ImageName":"title","logo1Skippable":"true","logo1Coordinate":"","logo1X":"512","logo1Y":"288","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"OggOnly","status":true,"description":"音声ファイルの再生にoggファイルのみを使用します。","parameters":{"deleteM4a":"false"}},
{"name":"StartUpFullScreen","status":true,"description":"フルスクリーンで起動プラグイン","parameters":{"Shutdown":"シャットダウン","UseTitle":"true","UseGameEnd":"true","StartUpFullScreen":"フルスクリーンで起動"}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.5) プレイヤー移動禁止プラグイン","parameters":{"Default_Move_Flag":"10","Default_Menu_Flag":"false","Enter Flag":"false"}},
{"name":"AutoMessage","status":true,"description":"メッセージの自動送りを行います。","parameters":{"SwitchId":"9","WaitMilliseconds":"1000","WaitMillisecondsVariableId":"0"}},
{"name":"DP_MapZoom","status":true,"description":"マップの拡大率を制御します。","parameters":{"Base Scale":"1","Encount Effect":"true","Camera Controll":"true","Weather Patch":"true","Picture Size Fixation":"true","Old Focus":"false","Easing Function":"t"}},
{"name":"TMRegionPassable","status":true,"description":"その場所が通行可能かどうかをリージョンで設定できるようになります。","parameters":{"passableRegions":"1","dontPassRegions":"2","counterRegions":"0"}},
{"name":"DarkPlasma_AutoLineBreak","status":true,"description":"ウィンドウ幅を超える日本語文章を自動で折り返す","parameters":{"prohibitLineBreakBefore":",)]｝、〕〉》」』〙〗〟’”｠»ゝゞーァィゥェォッャュョヮヵヶぁぃぅぇぉっゃゅょゎゕゖㇰㇱㇲㇳㇴㇵㇶㇷㇸㇹㇷ゚ㇺㇻㇼㇽㇾㇿ々〻‐゠–〜～?!‼⁇⁈⁉・:;/。.","prohibitLineBreakAfter":"([｛〔〈《「『〘〖〝‘“｟«","ignoreAutoLineBreakWindows":"[]","lineWidthMargin":"4"}},
{"name":"EventInformation","status":false,"description":"v1.1.1 イベントの頭上に文字を表示したい時に使います","parameters":{}},
{"name":"HyperLink","status":true,"description":"ゲーム中に外部ページへのリンクを貼ります。","parameters":{"description":"↓こちらをクリック↓"}},
{"name":"AnotherNewGame","status":true,"description":"アナザーニューゲーム追加プラグイン","parameters":{"anotherDataList":"[\"{\\\"name\\\":\\\"企画書はこちら\\\",\\\"mapId\\\":\\\"11\\\",\\\"mapX\\\":\\\"1\\\",\\\"mapY\\\":\\\"1\\\",\\\"hidden\\\":\\\"false\\\",\\\"disable\\\":\\\"false\\\",\\\"addPosition\\\":\\\"2\\\",\\\"demoWaitFrame\\\":\\\"0\\\",\\\"switchId\\\":\\\"0\\\",\\\"fileLoad\\\":\\\"false\\\",\\\"noFadeout\\\":\\\"false\\\"}\"]","manageNumber":""}},
{"name":"MoviePicture","status":true,"description":"動画のピクチャ表示プラグイン","parameters":{"動画音量種別":"none","終了時自動削除":"true","動画取得フォルダ":"","webm偽装拡張子":"","mp4偽装拡張子":""}}
];
